name: bitstamp
docker:
  image: slipalison/bitstamp-api-slipalison:latest
env:
  ASPNETCORE_ENVIRONMENT: Development
  database: post
  ConnectionStrings__postgre: User ID=bitstamp;Password=HZJqcT4It3liQC4O1H1p3cGUwhlX453U;Host=dpg-chn0kvm4dad21k1d9vn0-a.oregon-postgres.render.com;Port=5432;Database=bitstamp;Pooling=true;