// <auto-generated />
using System;
using Infra.Databases.SqlServers.BitstampData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(BitstampContext))]
    partial class BitstampContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.AggregationBook.BtcAsk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Microtimestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("InsertAt");

                    b.HasIndex("Microtimestamp");

                    b.HasIndex("Price");

                    b.HasIndex("Amount", "Price")
                        .IsUnique();

                    b.ToTable("BtcAsks");
                });

            modelBuilder.Entity("Domain.Models.AggregationBook.BtcBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Microtimestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("InsertAt");

                    b.HasIndex("Microtimestamp");

                    b.HasIndex("Price");

                    b.HasIndex("Amount", "Price")
                        .IsUnique();

                    b.ToTable("BtcBids");
                });

            modelBuilder.Entity("Domain.Models.AggregationBook.EthAsk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Microtimestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("InsertAt");

                    b.HasIndex("Microtimestamp");

                    b.HasIndex("Price");

                    b.HasIndex("Amount", "Price")
                        .IsUnique();

                    b.ToTable("EthAsks");
                });

            modelBuilder.Entity("Domain.Models.AggregationBook.EthBid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Microtimestamp")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("InsertAt");

                    b.HasIndex("Microtimestamp");

                    b.HasIndex("Price");

                    b.HasIndex("Amount", "Price")
                        .IsUnique();

                    b.ToTable("EthBids");
                });

            modelBuilder.Entity("Domain.Models.AggregationMetrics.Metric", b =>
                {
                    b.Property<decimal?>("MaxPrice")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "maxPrice");

                    b.Property<decimal?>("MediaAmount")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaAmount");

                    b.Property<decimal?>("MediaPrice")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaPrice");

                    b.Property<decimal?>("MediaPrice5")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "mediaPrice5");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "minPrice");

                    b.ToTable("Metrics");
                });

            modelBuilder.Entity("Domain.Models.AggregationMetrics.OrderItem", b =>
                {
                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Domain.Models.AggregationOrder.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("AmountTotal")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Crypto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("InsertAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Stock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InsertAt");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
