# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "addpostgre" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run unit tests coverage
      run: dotnet test /p:Configuration=Debug /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ThresholdType=line /p:CoverletOutput=./lcov --collect:"XPlat Code Coverage" --property:ExcludeByFile=\"*/Migrations/*\" test/UnitTest/UnitTest.csproj --no-build --no-restore --verbosity normal 
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: test/UnitTest/lcov.info

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: slipalison
        password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Build and publish Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        #no-cache: true
        #context: ./src/WebApi
        context: .
        #file: ./src/WebApi/DockerfilePublish
        file: DockerfilePublishApi
        push: true
        tags: slipalison/bitstamp-api-slipalison:latest
    
    - name: Build and publish Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: DockerfilePublishHost
        push: true
        tags: slipalison/bitstamp-host-slipalison:latest

    - name: Install Stryker.NET
      run: dotnet tool install -g dotnet-stryker

    - name: Run Stryker.NET
      run: dotnet stryker
    

