# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run unit tests coverage
      run: dotnet test /p:Configuration=Debug /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:ThresholdType=line /p:CoverletOutput=./lcov --collect:"XPlat Code Coverage" --property:ExcludeByFile=\"*/Migrations/*\" test/UnitTest/UnitTest.csproj --no-build --no-restore --verbosity normal 
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        # User defined upload name. Visible in Codecov UI
        #name: # optional
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: test/UnitTest/lcov.info
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        #flags: # optional
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        #fail_ci_if_error: # optional
    
    # - name: Install Stryker.NET
    #   run: dotnet tool install -g dotnet-stryker

    # - name: Run Stryker.NET
    #   run: dotnet stryker
    
    # - name: Publish report
    #   run: |
    #     mkdir -p ${{ github.workspace }}/StrykerOutput
    #     cp -R ./reports/. ${{ github.workspace }}/StrykerOutput
    #   # Upload report as an artifact
    
    # - name: Move reports to final directory
    #   run: |
    #     mv ${{ github.workspace }}/StrykerOutput ${{ github.workspace }}/StrykerOutput
    #       # Upload report as an artifact
    
    # - name: Upload Report
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: Stryker Report
    #     path: ${{ github.workspace }}/StrykerOutput

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: slipalison
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUBTOKEN }}
        # Specifies whether the given registry is ECR (auto, true or false)
        # ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        #logout: # optional, default is true

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v1
    #   with:
    #     username: slipalison
    #     password: ${{ secrets.DOCKERHUBTOKEN }}

    - name: Build and publish Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: /src/webapi
        push: true
        tags: slipalison/bitstamp-api-slipalison:latest
    
    - name: Build and publish Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context: /src/HostedServicesClient
        push: true
        tags: slipalison/bitstamp-slipalison:latest